/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProfileManagementSystem;

import ProfileManagementSystem.Entities.Student;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author geral
 */
public final class Profile extends javax.swing.JFrame {

    public Student student;
    Connection conn;

    public Profile() {
        initComponents();
        this.student = HomePage.student;
        conn = DbConnection.connect();

        loadStudentData();
    }

    public void loadStudentData() {
        firstnamefield.setText(student.first_name);
        lastnamefield.setText(student.last_name);
        middlenamefield.setText(student.middle_name);
        agefield.setText(String.valueOf(student.age));
        strandcombobox.setSelectedItem(student.strand);
        levelcombobox.setSelectedItem(String.valueOf(student.level));
        sectioncombobox.setSelectedItem(String.valueOf(student.section));
        birthday.setDate(student.birthday);
        schoolidfield.setText(student.school_id);
        numberfield.setText(student.contact_info);
        emailfield.setText(student.email);
        schoolg10field.setText(student.g10school);
        addressfield.setText(student.permanent_address);
        residencefield.setText(student.residence);
        provincefield1.setText(student.province);
        cityfield.setText(student.city);
        barangayfield.setText(student.barangay);
        zipcodfield.setText(String.valueOf(student.zipcode));
        
        lblFilename.setText(""); // reset filename
        lblFilename.setText(student.picture);
        if (!student.picture.isEmpty()) {
            lblImg.setIcon(new ImageIcon(student.picture));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        redbar = new javax.swing.JPanel();
        uphdlogo = new javax.swing.JLabel();
        barforedit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        leftside = new javax.swing.JPanel();
        homebutt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton()
        ;
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        NAME1 = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        middlenamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        middlename = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        strand = new javax.swing.JLabel();
        strandcombobox = new javax.swing.JComboBox<>();
        levelcombobox = new javax.swing.JComboBox<>();
        lblFilename = new javax.swing.JLabel();
        sectioncombobox = new javax.swing.JComboBox<>();
        section = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        gendercombobox = new javax.swing.JComboBox<>();
        bday = new javax.swing.JLabel();
        birthday = new com.toedter.calendar.JDateChooser();
        schoolidd = new javax.swing.JLabel();
        schoolidfield = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        numberfield = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        schoolg10 = new javax.swing.JLabel();
        schoolg10field = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        residence = new javax.swing.JLabel();
        residencefield = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        cityfield = new javax.swing.JTextField();
        province = new javax.swing.JLabel();
        barangayfield = new javax.swing.JTextField();
        barangay = new javax.swing.JLabel();
        zipcodfield = new javax.swing.JTextField();
        provincefield1 = new javax.swing.JTextField();
        zipcode1 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        level1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redbar.setBackground(new java.awt.Color(123, 21, 20));
        redbar.setForeground(new java.awt.Color(123, 21, 20));

        javax.swing.GroupLayout redbarLayout = new javax.swing.GroupLayout(redbar);
        redbar.setLayout(redbarLayout);
        redbarLayout.setHorizontalGroup(
            redbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1520, Short.MAX_VALUE)
        );
        redbarLayout.setVerticalGroup(
            redbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(redbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 40));
        getContentPane().add(uphdlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 320, -1));

        barforedit.setBackground(new java.awt.Color(153, 0, 0));
        barforedit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Currently viewing profile");
        barforedit.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 18, 225, -1));

        btnSave.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        btnSave.setText("Save Profile");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        barforedit.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 110, -1));

        getContentPane().add(barforedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 970, 60));

        leftside.setBackground(new java.awt.Color(255, 255, 255));
        leftside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebutt.setBackground(new java.awt.Color(204, 204, 204));
        homebutt.setBorder(null);
        homebutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebuttMouseClicked(evt);
            }
        });
        leftside.add(homebutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/profileredbutton (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        leftside.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/SCHED-removebg-preview (1).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        leftside.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/attendance-removebg-preview (1).png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        leftside.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/FAQs-removebg-preview (1).png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        leftside.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 80, 60));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/SHSlogo (1).png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        leftside.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, -1, -1));

        getContentPane().add(leftside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 860));

        //newest pa sa newest
        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(912, 1007));
        jPanel1.setPreferredSize(new java.awt.Dimension(912, 1007));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        NAME1.setText("NAME:");
        jPanel1.add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 170, 40));

        middlenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(middlenamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 170, 40));

        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 170, 40));

        firstname.setText("First Name");
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        middlename.setText("Middle Name");
        jPanel1.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        lastname.setText("Last Name");
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        strand.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        strand.setText("STRAND:");
        jPanel1.add(strand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        strandcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "HE", "AD", "HUMSS","GAS","STEM","ABM" }));
        strandcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(strandcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 170, 40));

        levelcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        jPanel1.add(levelcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 70, 40));

        lblFilename.setText("Selected Filename");
        jPanel1.add(lblFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, -1));

        sectioncombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6","7","8","9", "10", "11", "12", "13", "14", "15" }));
        jPanel1.add(sectioncombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 70, 40));

        section.setText("Section");
        jPanel1.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        age.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        age.setText("AGE:");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 50, -1));
        jPanel1.add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 50, 40));

        gender.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        gender.setText("GENDER:");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, 20));

        gendercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", }));
        jPanel1.add(gendercombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 110, 40));

        bday.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        bday.setText("BIRTHDAY:");
        jPanel1.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 20));

        birthday.setDateFormatString("MM/dd/YYYY");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 260, 40));

        schoolidd.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolidd.setText("SCHOOL ID:");
        jPanel1.add(schoolidd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 130, 20));

        schoolidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolidfieldActionPerformed(evt);
            }
        });
        jPanel1.add(schoolidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 270, 40));

        number.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        number.setText("CONTACT INFORMATION:");
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));
        jPanel1.add(numberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 40));

        email.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        email.setText("EMAIL ADDRESS:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 20));
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 310, 40));

        schoolg10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolg10.setText("SCHOOL (G10):");
        jPanel1.add(schoolg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 170, 20));

        schoolg10field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolg10fieldActionPerformed(evt);
            }
        });
        jPanel1.add(schoolg10field, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 250, 40));

        address.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        address.setText("PERMANENT ADDRESS:");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 300, 20));
        jPanel1.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 820, 40));

        residence.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        residence.setText("RESIDENCE ADDRESS:");
        jPanel1.add(residence, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 270, 20));
        jPanel1.add(residencefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 820, 40));

        city.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        city.setText("CITY");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, -1, 20));
        jPanel1.add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 170, 40));

        province.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        province.setText("PROVINCE");
        jPanel1.add(province, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 20));
        jPanel1.add(barangayfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 170, 40));

        barangay.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        barangay.setText("BARANGAY");
        jPanel1.add(barangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, 20));
        jPanel1.add(zipcodfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 170, 40));
        jPanel1.add(provincefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 170, 40));

        zipcode1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        zipcode1.setText("ZIP CODE");
        jPanel1.add(zipcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, 20));

        lblImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 200));

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, -1));

        level1.setText("Level");
        jPanel1.add(level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 970, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/maroon logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 320, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setText("Student Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(logout)
                .addGap(250, 250, 250))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(title))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(logout)))
                .addContainerGap(766, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 1360, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        SigninPage v = new SigninPage();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
      
    }//GEN-LAST:event_btnSaveMouseClicked

    private void homebuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttMouseClicked
        HomePage v = new HomePage();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebuttMouseClicked

    private void middlenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenamefieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed

    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void schoolg10fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolg10fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolg10fieldActionPerformed

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void schoolidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolidfieldActionPerformed

    private void strandcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandcomboboxActionPerformed

    }//GEN-LAST:event_strandcomboboxActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
//        Profile v = new Profile();
//        v.setVisible (true);
//        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Schedule v = new Schedule();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Attendancee1 v = new Attendancee1();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        FAQs v = new FAQs();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        HomePage v = new HomePage();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String sql = "update students set "
                + "first_name = ? "
                + ",last_name = ? "
                + ",middle_name = ? "
                + ",strand = ? "
                + ",level = ? "
                + ",section = ? "
                + ",age = ? "
                + ",gender = ? "
                + ", birthday= ? "
                + ",school_id = ? "
                + ",contact_info = ? "
                + ",email = ? "
                + ",permanent_address = ? "
                + ",present_address = ? "
                + ",province = ? "
                + ",city = ? "
                + ",barangay = ? "
                + ",zip_code = ? "
                + ",picture = ? "
                + " where id = " + this.student.id;
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, firstnamefield.getText());
            pst.setString(2, lastnamefield.getText());
            pst.setString(3, middlenamefield.getText());
            pst.setString(4, (String) strandcombobox.getSelectedItem());
            pst.setInt(5, Integer.parseInt(levelcombobox.getSelectedItem().toString()));
            pst.setInt(6, Integer.parseInt(sectioncombobox.getSelectedItem().toString()));
            pst.setInt(7, Integer.parseInt(agefield.getText()));
            pst.setString(8, gendercombobox.getSelectedItem().toString());
            pst.setDate(9, new Date(birthday.getDate().getTime()));
            pst.setString(10, schoolidfield.getText());
            pst.setString(11, numberfield.getText());
            pst.setString(12, emailfield.getText());
            pst.setString(13, addressfield.getText());
            pst.setString(14, residencefield.getText());
            pst.setString(15, provincefield1.getText());
            pst.setString(16, cityfield.getText());
            pst.setString(17, barangayfield.getText());
            pst.setInt(18, Integer.parseInt(zipcodfield.getText()));
            pst.setString(19, lblFilename.getText());
            pst.executeUpdate();

            reloadStudent();

            JOptionPane.showMessageDialog(null, "Profile Successfully Updated!");
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileFilter ff = new FileNameExtensionFilter("images", "jpeg");
        fc.addChoosableFileFilter(ff);
        int open = fc.showOpenDialog(this);

        if (open == javax.swing.JFileChooser.APPROVE_OPTION) {

            java.io.File path = fc.getSelectedFile();

            String file_name = path.toString();

            lblFilename.setText(file_name);

            BufferedImage bi; // bi is the object of the class BufferedImage
            try {
                bi = ImageIO.read(path); // path is your file or image path
                lblImg.setIcon(new ImageIcon(bi));
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reloadStudent() {
        try {
            ResultSet rs = conn.createStatement().executeQuery("select * from students where id = " + HomePage.studentId);
            if (rs.next()) {
                HomePage.student = Student.fromResultSet(rs);
                this.student = HomePage.student;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agefield;
    private javax.swing.JLabel barangay;
    private javax.swing.JTextField barangayfield;
    private javax.swing.JPanel barforedit;
    private javax.swing.JLabel bday;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> gendercombobox;
    private javax.swing.JButton homebutt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastname;
    public static javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lblFilename;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel leftside;
    private javax.swing.JLabel level1;
    private javax.swing.JComboBox<String> levelcombobox;
    private javax.swing.JButton logout;
    private javax.swing.JLabel middlename;
    public static javax.swing.JTextField middlenamefield;
    private javax.swing.JLabel number;
    private javax.swing.JTextField numberfield;
    private javax.swing.JLabel province;
    private javax.swing.JTextField provincefield1;
    private javax.swing.JPanel redbar;
    private javax.swing.JLabel residence;
    private javax.swing.JTextField residencefield;
    private javax.swing.JLabel schoolg10;
    private javax.swing.JTextField schoolg10field;
    private javax.swing.JLabel schoolidd;
    private javax.swing.JTextField schoolidfield;
    private javax.swing.JLabel section;
    private javax.swing.JComboBox<String> sectioncombobox;
    private javax.swing.JLabel strand;
    private javax.swing.JComboBox<String> strandcombobox;
    private javax.swing.JLabel title;
    private javax.swing.JLabel uphdlogo;
    private javax.swing.JLabel zipcode1;
    private javax.swing.JTextField zipcodfield;
    // End of variables declaration//GEN-END:variables
}
