/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProfileManagementSystem;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import static java.awt.GridBagConstraints.BOTH;
import javax.swing.BorderFactory;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.print.attribute.standard.DateTimeAtCompleted;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author geral
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form signup2
     */
    public SignupPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                // Calculate the center position of the panel
                int centerX = getWidth() / 2 ;
                int centerY = (int) (getHeight() / 3.5); // Casting to double before division

                // Calculate the diagonal distance from the center to the corner
                double diagonalLength = Math.sqrt(Math.pow(getWidth(), 2) + Math.pow(getHeight(), 2));

                // Adjust the start and end colors here
                Color color1 = Color.decode("#7B1514"); // Example start color
                Color color2 = Color.decode("#FFFFFF"); // Example end color

                // Calculate the start and end positions for the gradient based on the center
                GradientPaint gradient = new GradientPaint(
                    centerX, centerY, color1, // Start position and color
                    (float) (centerX + diagonalLength / 2), (float) (centerY + diagonalLength / 2), color2); // End position and color

                Graphics2D g2d = (Graphics2D) g;
                g2d.setPaint(gradient);
                g2d.fillRect(0, 0, getWidth(), getHeight()); // Fill the entire panel with gradient
            }
        };
        NAME1 = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        middlenamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        middlename = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        strand = new javax.swing.JLabel();
        strandcombobox = new javax.swing.JComboBox<>();
        levelcombobox = new javax.swing.JComboBox<>();
        level = new javax.swing.JLabel();
        sectioncombobox = new javax.swing.JComboBox<>();
        section = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        gendercombobox = new javax.swing.JComboBox<>();
        bday = new javax.swing.JLabel();
        birthday = new com.toedter.calendar.JDateChooser();
        schoolidd = new javax.swing.JLabel();
        schoolidfield = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        numberfield = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        schoolg10 = new javax.swing.JLabel();
        schoolg10field = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        residence = new javax.swing.JLabel();
        residencefield = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        cityfield = new javax.swing.JTextField();
        province = new javax.swing.JLabel();
        provincefield = new javax.swing.JTextField();
        barangay = new javax.swing.JLabel();
        zipcodefield = new javax.swing.JTextField();
        USERNAME = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        zipcode2 = new javax.swing.JLabel();
        pass1 = new javax.swing.JTextField();
        zipcode3 = new javax.swing.JLabel();
        pass2 = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        zipcode1 = new javax.swing.JLabel();
        barangayField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student-Profile SignUp");
        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagementSystem/photos/UPH-HEADER-YELLOW.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 180));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Have an account?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, -1, -1));

        //newest pa sa newest
        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(898, 1007));
        jPanel1.setPreferredSize(new java.awt.Dimension(898, 1007));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        NAME1.setForeground(new java.awt.Color(255, 255, 255));
        NAME1.setText("NAME:");
        jPanel1.add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 170, 40));

        middlenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(middlenamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 40));

        lastnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 170, 40));

        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setText("First Name");
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        middlename.setForeground(new java.awt.Color(255, 255, 255));
        middlename.setText("Middle Name");
        jPanel1.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setText("Last Name");
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        strand.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        strand.setForeground(new java.awt.Color(255, 255, 255));
        strand.setText("STRAND:");
        jPanel1.add(strand, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        strandcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "HE", "AD", "HUMSS","GAS","STEM","ABM" }));
        strandcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(strandcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, 40));

        levelcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        jPanel1.add(levelcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 70, 40));

        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("Level");
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        sectioncombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04","05","06","07","08","09", "10", "11", "12", "13", "14", "15" }));
        jPanel1.add(sectioncombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 70, 40));

        section.setForeground(new java.awt.Color(255, 255, 255));
        section.setText("Section");
        jPanel1.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        age.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("AGE:");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 50, -1));
        jPanel1.add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 50, 40));

        gender.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("GENDER:");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 20));

        gendercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", }));
        jPanel1.add(gendercombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 110, 40));

        bday.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        bday.setForeground(new java.awt.Color(255, 255, 255));
        bday.setText("BIRTHDAY:");
        jPanel1.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        birthday.setDateFormatString("YYYY-MM-dd");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 40));

        schoolidd.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolidd.setForeground(new java.awt.Color(255, 255, 255));
        schoolidd.setText("SCHOOL ID:");
        jPanel1.add(schoolidd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 130, 20));

        schoolidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolidfieldActionPerformed(evt);
            }
        });
        jPanel1.add(schoolidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 240, 40));

        number.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        number.setForeground(new java.awt.Color(255, 255, 255));
        number.setText("CONTACT INFORMATION:");
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(numberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 240, 40));

        email.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("EMAIL ADDRESS:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 310, 40));

        schoolg10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolg10.setForeground(new java.awt.Color(255, 255, 255));
        schoolg10.setText("SCHOOL (G10):");
        jPanel1.add(schoolg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 140, 20));

        schoolg10field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolg10fieldActionPerformed(evt);
            }
        });
        jPanel1.add(schoolg10field, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 250, 40));

        address.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("PERMANENT ADDRESS:");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 300, -1));
        jPanel1.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 820, 40));

        residence.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        residence.setForeground(new java.awt.Color(255, 255, 255));
        residence.setText("RESIDENCE ADDRESS:");
        jPanel1.add(residence, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 270, -1));
        jPanel1.add(residencefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 820, 40));

        city.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setText("CITY");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        cityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityfieldActionPerformed(evt);
            }
        });
        jPanel1.add(cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 180, 40));

        province.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        province.setForeground(new java.awt.Color(255, 255, 255));
        province.setText("PROVINCE");
        jPanel1.add(province, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));
        jPanel1.add(provincefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 180, 40));

        barangay.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        barangay.setForeground(new java.awt.Color(255, 255, 255));
        barangay.setText("BARANGAY");
        jPanel1.add(barangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));
        jPanel1.add(zipcodefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 190, 40));

        USERNAME.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        USERNAME.setText("USERNAME");
        jPanel1.add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));
        jPanel1.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 260, 40));

        zipcode2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        zipcode2.setForeground(new java.awt.Color(255, 255, 255));
        zipcode2.setText("PASSWORD");
        jPanel1.add(zipcode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));
        jPanel1.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, 260, 40));

        zipcode3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        zipcode3.setForeground(new java.awt.Color(255, 255, 255));
        zipcode3.setText("RE-ENTER PASSWORD");
        jPanel1.add(zipcode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, -1, -1));
        jPanel1.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 260, 40));

        btnSignup.setBackground(new java.awt.Color(0, 0, 0));
        btnSignup.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign Up");
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
        });
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 920, 260, 40));

        zipcode1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        zipcode1.setForeground(new java.awt.Color(255, 255, 255));
        zipcode1.setText("ZIP CODE");
        jPanel1.add(zipcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));
        jPanel1.add(barangayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 210, 40));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 910, 590));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagementSystem/photos/bgperps.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1500, 900));
        jLabel2.setMinimumSize(new java.awt.Dimension(1500, 900));
        jLabel2.setPreferredSize(new java.awt.Dimension(1500, 900));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SigninPage x = new SigninPage();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void middlenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenamefieldActionPerformed

    private void lastnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefieldActionPerformed

    }//GEN-LAST:event_lastnamefieldActionPerformed

    private void strandcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandcomboboxActionPerformed

    }//GEN-LAST:event_strandcomboboxActionPerformed

    private void schoolidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolidfieldActionPerformed

    private void schoolg10fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolg10fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolg10fieldActionPerformed

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        HomePage x = new HomePage();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignupMouseClicked

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed

        try {
            String fname = firstnamefield.getText();
            String mname = middlenamefield.getText();
            String lname = lastnamefield.getText();
            int age = Integer.parseInt(agefield.getText());
            String schoolId = schoolidfield.getText();
            String number = numberfield.getText();
            Date birthday = this.birthday.getDate();
            String gender = gendercombobox.getSelectedItem().toString();
            String strand = strandcombobox.getSelectedItem().toString();
            int level = Integer.parseInt(levelcombobox.getSelectedItem().toString());
            int section = Integer.parseInt(sectioncombobox.getSelectedItem().toString());
            String email = emailfield.getText();
            String g10school = schoolg10field.getText();
            String address = addressfield.getText();
            String residence = residencefield.getText();
            String city = cityfield.getText();
            String province = provincefield.getText();
            int zipcode = Integer.parseInt(zipcodefield.getText());
            String barangay = barangayField.getText();
            String username = usernamefield.getText();
            String password = pass1.getText();
            String confirmPassword = pass2.getText();

            if (firstnamefield.getText().isEmpty() || middlenamefield.getText().isEmpty() || lastnamefield.getText().isEmpty() || agefield.getText().isEmpty() || schoolidfield.getText().isEmpty() || numberfield.getText().isEmpty() || emailfield.getText().isEmpty() || schoolg10field.getText().isEmpty() || addressfield.getText().isEmpty() || residencefield.getText().isEmpty() || cityfield.getText().isEmpty() || provincefield.getText().isEmpty() || zipcodefield.getText().isEmpty()) {
                showMessageDialog(null, "Please fill in all fields.");

            } else if (!password.equals(confirmPassword)) {
                showMessageDialog(null, "Passwords do not match.");
            } else {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/profile_management", "root", "");
                Statement stmt = con.createStatement();
                String query = "SELECT * FROM users WHERE username = '" + username + "'";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()) {
                    showMessageDialog(null, "Username already exists");
                } else {
                    // insert student
                    String insertStudentSql = "INSERT INTO students "
                            + "(first_name, middle_name, last_name, age, gender, birthday, strand, level, section, school_id, contact_info, email, "
                            + " former_school, permanent_address, present_address, city, province, zip_code, barangay)"
                            + " VALUES "
                            + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ? , ?, ? , ? , ?, ?, ?, ?, ?, ?)";
                    PreparedStatement preparedStmt = con.prepareStatement(insertStudentSql, Statement.RETURN_GENERATED_KEYS);
                    preparedStmt.setString(1, fname);
                    preparedStmt.setString(2, mname);
                    preparedStmt.setString(3, lname);
                    preparedStmt.setInt(4, age);
                    preparedStmt.setString(5, gender);
                    preparedStmt.setDate(6, new java.sql.Date(birthday.getTime()));
                    preparedStmt.setString(7, strand);
                    preparedStmt.setInt(8, level);
                    preparedStmt.setInt(9, section);
                    preparedStmt.setString(10, schoolId);
                    preparedStmt.setString(11, number);
                    preparedStmt.setString(12, email);
                    preparedStmt.setString(13, g10school);
                    preparedStmt.setString(14, address);
                    preparedStmt.setString(15, residence);
                    preparedStmt.setString(16, city);
                    preparedStmt.setString(17, province);
                    preparedStmt.setInt(18, zipcode);
                    preparedStmt.setString(19, barangay);
                    preparedStmt.executeUpdate();
                    int student_id = 0;

                    ResultSet rsx = preparedStmt.getGeneratedKeys();
                    if (rsx.next()) {
                        student_id = rsx.getInt(1);
                    } 

                    // insert user
                    String insertUserSql = "INSERT INTO users "
                            + "(name, username, password, student_id)"
                            + " VALUES (?, ?, ?, ?)";
                    PreparedStatement st2 = con.prepareStatement(insertUserSql);
                    st2.setString(1, fname + " " + lname);
                    st2.setString(2, username);
                    st2.setString(3, password);
                    st2.setInt(4, student_id);
                    st2.executeUpdate();
                    
                    showMessageDialog(null, "Account created successfully");

                    SigninPage v = new SigninPage();
                    v.setVisible(true);
                    this.dispose();
                }
            }
        } catch (Exception e) {
            showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnSignupActionPerformed

    private void cityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agefield;
    private javax.swing.JLabel barangay;
    private javax.swing.JTextField barangayField;
    private javax.swing.JLabel bday;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> gendercombobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastname;
    public static javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel level;
    private javax.swing.JComboBox<String> levelcombobox;
    private javax.swing.JLabel middlename;
    public static javax.swing.JTextField middlenamefield;
    private javax.swing.JLabel number;
    private javax.swing.JTextField numberfield;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField pass2;
    private javax.swing.JLabel province;
    private javax.swing.JTextField provincefield;
    private javax.swing.JLabel residence;
    private javax.swing.JTextField residencefield;
    private javax.swing.JLabel schoolg10;
    private javax.swing.JTextField schoolg10field;
    private javax.swing.JLabel schoolidd;
    private javax.swing.JTextField schoolidfield;
    private javax.swing.JLabel section;
    private javax.swing.JComboBox<String> sectioncombobox;
    private javax.swing.JLabel strand;
    private javax.swing.JComboBox<String> strandcombobox;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel zipcode1;
    private javax.swing.JLabel zipcode2;
    private javax.swing.JLabel zipcode3;
    private javax.swing.JTextField zipcodefield;
    // End of variables declaration//GEN-END:variables
}
