/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProfileManagementSystem;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.BorderFactory;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author geral
 */
public class signup2 extends javax.swing.JFrame {

    /**
     * Creates new form signup2
     */
    public signup2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(){@Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                // Calculate the center position of the panel
                int centerX = getWidth() / 2 ;
                int centerY = (int) (getHeight() / 3.5); // Casting to double before division

                // Calculate the diagonal distance from the center to the corner
                double diagonalLength = Math.sqrt(Math.pow(getWidth(), 2) + Math.pow(getHeight(), 2));

                // Adjust the start and end colors here
                Color color1 = Color.decode("#7B1514"); // Example start color
                Color color2 = Color.decode("#FFFFFF"); // Example end color

                // Calculate the start and end positions for the gradient based on the center
                GradientPaint gradient = new GradientPaint(
                    centerX, centerY, color1, // Start position and color
                    (float) (centerX + diagonalLength / 2), (float) (centerY + diagonalLength / 2), color2); // End position and color

                Graphics2D g2d = (Graphics2D) g;
                g2d.setPaint(gradient);
                g2d.fillRect(0, 0, getWidth(), getHeight()); // Fill the entire panel with gradient
            }

        };
        txtFirstName = new javax.swing.JTextField();
        NAME1 = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        passwordd = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        schoolg10 = new javax.swing.JLabel();
        schoolfield2 = new javax.swing.JTextField();
        birthday = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        permaaddress = new javax.swing.JLabel();
        permaaddressfield = new javax.swing.JTextField();
        residence = new javax.swing.JLabel();
        residencefield = new javax.swing.JTextField();
        emergencycontact = new javax.swing.JLabel();
        zipcodefield = new javax.swing.JTextField();
        gender1 = new javax.swing.JLabel();
        Contactinfo = new javax.swing.JLabel();
        strandfield1 = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        strandfield2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        strand3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        bday = new com.toedter.calendar.JDateChooser();
        gender = new javax.swing.JComboBox<>();
        emergencycontact1 = new javax.swing.JLabel();
        provincefield = new javax.swing.JTextField();
        emergencycontact2 = new javax.swing.JLabel();
        Cityfield = new javax.swing.JTextField();
        bttnSignup = new javax.swing.JButton();
        reenterpass = new javax.swing.JTextField();
        reenterpassword = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        schoolfield3 = new javax.swing.JTextField();
        schoolg11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sign In");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 800, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagementSystem/UPH Header -2 (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Have an account?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 800, -1, -1));

        jPanel1.setMinimumSize(new java.awt.Dimension(912, 1007));
        jPanel1.setPreferredSize(new java.awt.Dimension(912, 1007));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 40));

        NAME1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        NAME1.setForeground(new java.awt.Color(255, 255, 255));
        NAME1.setText("NAME:");
        jPanel1.add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 170, 40));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 170, 40));

        username.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("USERNAME:");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, 20));
        jPanel1.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 270, 40));

        passwordd.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        passwordd.setForeground(new java.awt.Color(255, 255, 255));
        passwordd.setText("PASSWORD:");
        jPanel1.add(passwordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, -1, -1));
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, 270, 40));

        schoolg10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolg10.setForeground(new java.awt.Color(255, 255, 255));
        schoolg10.setText("SCHOOL (G10):");
        jPanel1.add(schoolg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 130, 20));

        schoolfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolfield2ActionPerformed(evt);
            }
        });
        jPanel1.add(schoolfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 240, 40));

        birthday.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        birthday.setForeground(new java.awt.Color(255, 255, 255));
        birthday.setText("BIRTHDAY:");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        age.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("AGE:");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 40, -1));

        permaaddress.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        permaaddress.setForeground(new java.awt.Color(255, 255, 255));
        permaaddress.setText("PERMANENT ADDRESS:");
        jPanel1.add(permaaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, -1));
        jPanel1.add(permaaddressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 820, 40));

        residence.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        residence.setForeground(new java.awt.Color(255, 255, 255));
        residence.setText("RESIDENCE ADDRESS:");
        jPanel1.add(residence, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 270, -1));
        jPanel1.add(residencefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 820, 40));

        emergencycontact.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        emergencycontact.setForeground(new java.awt.Color(255, 255, 255));
        emergencycontact.setText("ZIP CODE");
        jPanel1.add(emergencycontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));
        jPanel1.add(zipcodefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 170, 40));

        gender1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        gender1.setForeground(new java.awt.Color(255, 255, 255));
        gender1.setText("GENDER:");
        jPanel1.add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, 20));

        Contactinfo.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        Contactinfo.setForeground(new java.awt.Color(255, 255, 255));
        Contactinfo.setText("CONTACT INFORMATION:");
        jPanel1.add(Contactinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(strandfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 310, 40));

        Email.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("EMAIL ADDRESS:");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));
        jPanel1.add(strandfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Section");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 50, 40));

        strand3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        strand3.setForeground(new java.awt.Color(255, 255, 255));
        strand3.setText("STRAND:");
        jPanel1.add(strand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04","05","06","07","08","09", "10", "11", "12", "13", "14", "15" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 70, 40));

        bday.setDateFormatString("MM/dd/YYYY");
        jPanel1.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 40));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 110, 40));

        emergencycontact1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        emergencycontact1.setForeground(new java.awt.Color(255, 255, 255));
        emergencycontact1.setText("PROVINCE");
        jPanel1.add(emergencycontact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));
        jPanel1.add(provincefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 170, 40));

        emergencycontact2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        emergencycontact2.setForeground(new java.awt.Color(255, 255, 255));
        emergencycontact2.setText("CITY");
        jPanel1.add(emergencycontact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));
        jPanel1.add(Cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 170, 40));

        bttnSignup.setText("Sign Up");
        bttnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(bttnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 950, 150, 40));
        jPanel1.add(reenterpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, 270, 40));

        reenterpassword.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        reenterpassword.setForeground(new java.awt.Color(255, 255, 255));
        reenterpassword.setText("RE-ENTER PASSWORD:");
        jPanel1.add(reenterpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 840, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "HE", "AD", "HUMSS","GAS","STEM","ABM" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 40));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 70, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Level");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        schoolfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolfield3ActionPerformed(evt);
            }
        });
        jPanel1.add(schoolfield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 240, 40));

        schoolg11.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        schoolg11.setForeground(new java.awt.Color(255, 255, 255));
        schoolg11.setText("SCHOOL ID:");
        jPanel1.add(schoolg11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 130, 20));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 910, 590));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagementSystem/STUDENT-PROFILE MANAGEMENT SYSTEM DESIGN.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1500, 900));
        jLabel2.setMinimumSize(new java.awt.Dimension(1500, 900));
        jLabel2.setPreferredSize(new java.awt.Dimension(1500, 900));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 2090, 1120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void schoolfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolfield2ActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed

    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleNameActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    sigin x = new sigin();
    x.setVisible (true);
    this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void schoolfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolfield3ActionPerformed

    private void bttnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSignupActionPerformed

    }//GEN-LAST:event_bttnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cityfield;
    private javax.swing.JLabel Contactinfo;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel age;
    private com.toedter.calendar.JDateChooser bday;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton bttnSignup;
    private javax.swing.JLabel emergencycontact;
    private javax.swing.JLabel emergencycontact1;
    private javax.swing.JLabel emergencycontact2;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passwordd;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JLabel permaaddress;
    private javax.swing.JTextField permaaddressfield;
    private javax.swing.JTextField provincefield;
    private javax.swing.JTextField reenterpass;
    private javax.swing.JLabel reenterpassword;
    private javax.swing.JLabel residence;
    private javax.swing.JTextField residencefield;
    private javax.swing.JTextField schoolfield2;
    private javax.swing.JTextField schoolfield3;
    private javax.swing.JLabel schoolg10;
    private javax.swing.JLabel schoolg11;
    private javax.swing.JLabel strand3;
    private javax.swing.JTextField strandfield1;
    private javax.swing.JTextField strandfield2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    public static javax.swing.JTextField txtLastName;
    public static javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField userfield;
    private javax.swing.JLabel username;
    private javax.swing.JTextField zipcodefield;
    // End of variables declaration//GEN-END:variables
}
